In [1]:
import pandas as pd
#身長と体重のデータを読み込む
children = pd.read_csv("https://raw.githubusercontent.com/futurebridge/ZukaiML/master/children.csv",encoding="SHIFT-JIS")

#読み込んだデータの表示
children

      年齢    身長
0   4.47  1022
1   2.11   835
2   3.56   958
3   2.91   909
4   4.25  1044
5   3.93  1023
6   4.20   997
7   3.99  1033
8   4.13  1035
9   4.33  1057
10  2.32   877
11  2.37   851
12  2.17   879
13  2.56   881
14  2.38   912

In [2]:
import numpy as np

#x,yの平均を求める
x,y = np.mean(children)
print (x,y)

3.312 954.2

In [35]:
#共分散を求める
#データ個数分だけ (x-x平均)x(y-y平均)を繰り返す
sum=0
for i in range(0,len(children)):
  sum += ((children["年齢"][i]-x)*(children["身長"][i]-y))
  print(i,"年齢",children["年齢"][i],"身長",children["身長"][i],"身長×年齢",np.round(sum,3))

#データ個数で割った値を返す
cov_a = sum/len(children)

print ("共分散:",np.round(cov_a,3))

0 年齢 4.47 身長 1022 身長×年齢 78.512
1 年齢 2.11 身長 835 身長×年齢 221.791
2 年齢 3.56 身長 958 身長×年齢 222.733
3 年齢 2.91 身長 909 身長×年齢 240.904
4 年齢 4.25 身長 1044 身長×年齢 325.136
5 年齢 3.93 身長 1023 身長×年齢 367.654
6 年齢 4.2 身長 997 身長×年齢 405.661
7 年齢 3.99 身長 1033 身長×年齢 459.087
8 年齢 4.13 身長 1035 身長×年齢 525.182
9 年齢 4.33 身長 1057 身長×年齢 629.832
10 年齢 2.32 身長 877 身長×年齢 706.414
11 年齢 2.37 身長 851 身長×年齢 803.629
12 年齢 2.17 身長 879 身長×年齢 889.507
13 年齢 2.56 身長 881 身長×年齢 944.554
14 年齢 2.38 身長 912 身長×年齢 983.884
共分散: 65.592

In [4]:

#年齢と身長の標準偏差を求める
a_std,b_std=np.std(children)

#相関係数を求める
#相関係数 = (共分散)/(身長の標準偏差x年齢の標準偏差)

print ("相関係数:",cov_a/(a_std*b_std))

相関係数: 0.963024154927

In [5]:
#最小二乗法による傾きa と　切片bを求める

#分散を求める
a_var,b_var = np.var(children)

#傾きa = 共分散/分散
a = cov_a/a_var

#切片 b= y平均 - a x x平均
b = y - a * x

print ("傾きa",a, "切片b",b)

傾きa 83.1401617706 切片b 678.839784216

In [6]:
import pandas as pd
#身長と体重のデータを読み込む
childrentest = pd.read_csv("https://raw.githubusercontent.com/futurebridge/ZukaiML/master/childrentest.csv",encoding="SHIFT-JIS")

#読み込んだテストデータの表示
childrentest

      年齢   身長
0   0.67  676
1   0.70  642
2   0.48  674
3   0.39  570
4   1.07  746
5   0.62  666
6   0.80  732
7   1.25  719
8   0.92  729
9   1.61  830
10  0.93  772
11  1.41  812
12  3.62  961
13  2.99  965
14  3.58  959

In [37]:


#入力：テストデータの年齢、出力：身長
for i in range(0,len(childrentest)):
  test= ((childrentest["年齢"][i]*a)+b)
  print(i,"年齢:",childrentest["年齢"][i],"身長(実測値):",childrentest["身長"][i],"身長(予測値):",round(test,2)
       ,"残差:",childrentest["身長"][i]-round(test,2))

0 年齢: 0.67 身長(実測値): 676 身長(予測値): 734.54 残差: -58.54
1 年齢: 0.7 身長(実測値): 642 身長(予測値): 737.04 残差: -95.04
2 年齢: 0.48 身長(実測値): 674 身長(予測値): 718.75 残差: -44.75
3 年齢: 0.39 身長(実測値): 570 身長(予測値): 711.26 残差: -141.26
4 年齢: 1.07 身長(実測値): 746 身長(予測値): 767.8 残差: -21.8
5 年齢: 0.62 身長(実測値): 666 身長(予測値): 730.39 残差: -64.39
6 年齢: 0.8 身長(実測値): 732 身長(予測値): 745.35 残差: -13.35
7 年齢: 1.25 身長(実測値): 719 身長(予測値): 782.76 残差: -63.76
8 年齢: 0.92 身長(実測値): 729 身長(予測値): 755.33 残差: -26.33
9 年齢: 1.61 身長(実測値): 830 身長(予測値): 812.7 残差: 17.3
10 年齢: 0.93 身長(実測値): 772 身長(予測値): 756.16 残差: 15.84
11 年齢: 1.41 身長(実測値): 812 身長(予測値): 796.07 残差: 15.93
12 年齢: 3.62 身長(実測値): 961 身長(予測値): 979.81 残差: -18.81
13 年齢: 2.99 身長(実測値): 965 身長(予測値): 927.43 残差: 37.57
14 年齢: 3.58 身長(実測値): 959 身長(予測値): 976.48 残差: -17.48

In [ ]:

#説明変数の抽出
X = children["年齢"] 
#目的変数の抽出
Y = children["身長"] 


#ライブラリの導入
#エラーになる場合、anaconda promptからpip install statsmodels
import statsmodels.api as smf
#定数表示
X1=smf.add_constant(X) 
#OLS(最小二乗法)でモデル作成
model = smf.OLS(Y,X1)
#model.fitで実際の計算
result = model.fit()
#結果表示
result.summary()

In [41]:
##決定係数
#残差平方和,回帰平方和、全体平方和を求める
z_sum=0
k_sum=0
t_sum=0
for i in range(0,len(children)):
    #残差平方和 y(実測値) - 予測値
    z_sum += (children["身長"][i]-(children["年齢"][i]*a+b))**2
    #回帰平方和 予測値 - 平均
    k_sum+= ((children["年齢"][i]*a+b)-y)**2
    #全体平方和 y(実測値) - 平均
    t_sum+= ((children["身長"][i])-y)**2


#    print ("残差平方和:",z_sum,"回帰平方和:",k_sum,"全体平方和:",t_sum)

#決定係数を求める
print ("決定係数 回帰平方和/全体平方和", np.round(k_sum/t_sum,3), "決定係数 1-残差平方和/全体平方和",1 - round(z_sum/t_sum,3))

決定係数 回帰平方和/全体平方和 0.927 決定係数 1-残差平方和/全体平方和 0.927

In [42]:
#標準誤差を求める

#残差平方和を自由度を引いた個数でかける

se1=z_sum*(1/(len(children)-2))

# x-x平均の平方和
x_sum=0
for i in range(0,len(children)):
    x_sum += (children["年齢"][i]-x)**2

se2=np.sqrt((se1/x_sum))
    
#標準誤差を求める
print ("標準誤差:",round(se2,3)

標準誤差: 6.45095310311

In [45]:
#t値を求める 
tval = a/se2
print ("t値:",round(tval,3))

t値: 12.888

In [44]:
#t値が１の場合のp値
from scipy.stats import norm
1-norm.cdf(3, 0, 1)

0.0013498980316301035

In [47]:
#重回帰分析
import pandas as pd
#身長と体重のデータを読み込む
childrenm = pd.read_csv("childrenm.csv",encoding="SHIFT-JIS")

In [48]:
childrenm

      身長    年齢    体重   手長  手首
0   1022  4.47  20.6  111  39
1    835  2.11  11.8   97  27
2    958  3.56  13.6  107   2
3    909  2.91  12.4  104  28
4   1044  4.25  16.6  120   1
5   1023  3.93  16.2  118  26
6    997  4.20  14.6  110  39
7   1033  3.99  16.0  112   2
8   1035  4.13  17.6  120   9
9   1057  4.33  18.5  119   9
10   994  3.74  14.3  111  17
11  1110  4.47  22.9  120  43
12  1038  4.36  16.3  123  25
13  1049  4.21  15.9  112   7
14   877  2.32  12.6  104  28
15   851  2.37  12.6   97   9
16   879  2.17  12.8  100  25

In [49]:
#相関行列を求める
childrenm.corr()

          身長        年齢        体重        手長        手首
身長  1.000000  0.961929  0.848933  0.921505 -0.054059
年齢  0.961929  1.000000  0.800781  0.884119 -0.035522
体重  0.848933  0.800781  1.000000  0.747222  0.220878
手長  0.921505  0.884119  0.747222  1.000000 -0.074436
手首 -0.054059 -0.035522  0.220878 -0.074436  1.000000

In [50]:
#説明変数の抽出、身長以外を説明変数として利用
X = childrenm.drop("身長",1) 
#目的変数の抽出
Y = childrenm["身長"] 

#ライブラリの導入
#エラーになる場合、anaconda promptからpip install statsmodels
import statsmodels.api as smf
#定数表示
X1=smf.add_constant(X) 
#OLS(最小二乗法)でモデル作成
model1 = smf.OLS(Y,X1)
#model.fitで実際の計算
result = model1.fit()
#結果表示
result.summary()

C:\Users\kengo\Anaconda3\lib\site-packages\statsmodels\compat\pandas.py:56: FutureWarning: The pandas.core.datetools module is deprecated and will be removed in a future version. Please use the pandas.tseries module instead.
  from pandas.core import datetools
C:\Users\kengo\Anaconda3\lib\site-packages\scipy\stats\stats.py:1334: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=17
  "anyway, n=%i" % int(n))

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                     身長   R-squared:                       0.964
Model:                            OLS   Adj. R-squared:                  0.953
Method:                 Least Squares   F-statistic:                     81.27
Date:                Wed, 17 Apr 2019   Prob (F-statistic):           1.38e-08
Time:                        12:51:37   Log-Likelihood:                -70.268
No. Observations:                  17   AIC:                             150.5
Df Residuals:                      12   BIC:                             154.7
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const        416.5500     95.187      4.376      0.001     209.155     623.945
年齢            50.1660     12.468      4.024      0.002      23.000      77.331
体重             6.3704      2.748      2.318      0.039       0.383      12.358
手長             2.6463      1.172      2.258      0.043       0.093       5.200
手首            -0.4014      0.362     -1.107      0.290      -1.191       0.388
==============================================================================
Omnibus:                        0.584   Durbin-Watson:                   2.176
Prob(Omnibus):                  0.747   Jarque-Bera (JB):                0.600
Skew:                           0.120   Prob(JB):                        0.741
Kurtosis:                       2.111   Cond. No.                     2.50e+03
==============================================================================

Warnings:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 2.5e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [46]:
#説明変数の抽出、身長以外を説明変数として利用
#手長を除く
X = X.drop("手首",1) 

#ライブラリの導入
#エラーになる場合、anaconda promptからpip install statsmodels
import statsmodels.api as smf
#定数表示
X1=smf.add_constant(X) 
#OLS(最小二乗法)でモデル作成
model2 = smf.OLS(Y,X1)
#model.fitで実際の計算
result2 = model2.fit()
#結果表示
result2.summary()

NameError: name 'X' is not defined